controller_list:
  - name: fake_iiwa7_controller
    joints:
      - iiwa7_joint_1
      - iiwa7_joint_2
      - iiwa7_joint_3
      - iiwa7_joint_4
      - iiwa7_joint_5
      - iiwa7_joint_6
      - iiwa7_joint_7
  - name: fake_iiwa14_controller
    joints:
      - iiwa14_joint_1
      - iiwa14_joint_2
      - iiwa14_joint_3
      - iiwa14_joint_4
      - iiwa14_joint_5
      - iiwa14_joint_6
      - iiwa14_joint_7