iiwa7:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  
  
  # Controllers for singular joint ------------------------------------
  # 
 
  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_J1_controller:
    type: position_controllers/JointPositionController
    joint: iiwa7_joint_1

  PositionJointInterface_J2_controller:
    type: position_controllers/JointPositionController
    joint: iiwa7_joint_2
    
  PositionJointInterface_J3_controller:
    type: position_controllers/JointPositionController
    joint: iiwa7_joint_3
    
  PositionJointInterface_J4_controller:
    type: position_controllers/JointPositionController
    joint: iiwa7_joint_4
    
  PositionJointInterface_J5_controller:
    type: position_controllers/JointPositionController
    joint: iiwa7_joint_5
    
  PositionJointInterface_J6_controller:
    type: position_controllers/JointPositionController
    joint: iiwa7_joint_6
    
  PositionJointInterface_J7_controller:
    type: position_controllers/JointPositionController
    joint: iiwa7_joint_7
    
  # Trajectory Controllers ---------------------------------------
  #   
  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - iiwa7_joint_1
      - iiwa7_joint_2
      - iiwa7_joint_3
      - iiwa7_joint_4
      - iiwa7_joint_5
      - iiwa7_joint_6
      - iiwa7_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  500            # Override default
    action_monitor_rate: 500            # Override default
    stop_trajectory_duration: 0        # Override default
    
iiwa14:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  
  
  # Controllers for singular joint ------------------------------------
  # 
 
  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_J1_controller:
    type: position_controllers/JointPositionController
    joint: iiwa14_joint_1

  PositionJointInterface_J2_controller:
    type: position_controllers/JointPositionController
    joint: iiwa14_joint_2
    
  PositionJointInterface_J3_controller:
    type: position_controllers/JointPositionController
    joint: iiwa14_joint_3
    
  PositionJointInterface_J4_controller:
    type: position_controllers/JointPositionController
    joint: iiwa14_joint_4
    
  PositionJointInterface_J5_controller:
    type: position_controllers/JointPositionController
    joint: iiwa14_joint_5
    
  PositionJointInterface_J6_controller:
    type: position_controllers/JointPositionController
    joint: iiwa14_joint_6
    
  PositionJointInterface_J7_controller:
    type: position_controllers/JointPositionController
    joint: iiwa14_joint_7
    
  # Trajectory Controllers ---------------------------------------
  #   
  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - iiwa14_joint_1
      - iiwa14_joint_2
      - iiwa14_joint_3
      - iiwa14_joint_4
      - iiwa14_joint_5
      - iiwa14_joint_6
      - iiwa14_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  500            # Override default
    action_monitor_rate: 500            # Override default
    stop_trajectory_duration: 0        # Override default
